# -*- mode: python ; coding: utf-8 -*-
# EnergyLink System - Full Build with LINE Webhook Support

import os

a = Analysis(
    ['run_full_system.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('services', 'services'),
        ('projects', 'projects'),
        ('manager', 'manager'),
        ('cloudflared.exe', '.'),
        ('.env', '.'),
        ('data', 'data'),
    ],
    hiddenimports=[
        # Uvicorn
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # FastAPI / Starlette
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.responses',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'python_multipart',
        'multipart',
        # HTTP / ASGI
        'h11',
        'httptools',
        'websockets',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        # Pydantic
        'pydantic',
        'pydantic.deprecated',
        'pydantic.deprecated.decorator',
        # LINE Bot SDK
        'linebot',
        'linebot.api',
        'linebot.exceptions',
        'linebot.models',
        'linebot.models.events',
        'linebot.models.messages',
        'linebot.models.send_messages',
        'linebot.models.sources',
        # Modbus
        'pymodbus',
        'pymodbus.client',
        'pymodbus.client.tcp',
        'pymodbus.constants',
        'pymodbus.payload',
        'pymodbus.exceptions',
        # Database
        'sqlite3',
        # QR Code
        'qrcode',
        'qrcode.image',
        'qrcode.image.pil',
        # Others
        'json',
        'uuid',
        'secrets',
        'threading',
        'multiprocessing',
        'socket',
        'struct',
        'ctypes',
        'hmac',
        'hashlib',
        'base64',
        'traceback',
        'schedule',
        # Backend modules
        'services.backend.fastapi_app',
        'services.backend.shared_state',
        'services.backend.api.trend_api',
        'services.backend.api.history_api',
        'services.backend.api.project_init',
        'services.backend.api.system_events',
        'services.backend.api.persistence',
        'services.backend.api.import_tool',
        'services.backend.api.powerstudio_router',
        'services.backend.read_modbus.modbus_poller_final',
        # Alert module
        'services.backend.api.alert_module',
        'services.backend.api.alert_module.alert_engine',
        'services.backend.api.alert_module.alert_routes',
        'services.backend.api.alert_module.alert_manager',
        'services.backend.api.alert_module.rules_manager',
        'services.backend.api.alert_module.event_engine',
        'services.backend.api.alert_module.offline_monitor_task',
        # LINE integration
        'services.backend.integrations.line_bot',
        'services.backend.integrations.line_bot.line_config',
        'services.backend.integrations.line_bot.line_service',
        'services.backend.integrations.line_bot.line_routes',
        'services.backend.integrations.line_bot.webhook_handler',
        'services.backend.integrations.line_bot.alert_manager',
        'services.backend.integrations.line_bot.user_preferences',
        'services.backend.integrations.line_bot.scheduler',
        # LINE API (old)
        'services.backend.api.line.router',
        'services.backend.api.line.line_client',
        'services.backend.api.line.bot_logic',
        'services.backend.api.line.config',
        # Other routers
        'services.backend.api.photoview.photoview_router',
        'services.backend.api.report_builder.report_router',
        'services.backend.api.report_builder.template_router',
        'services.backend.api.billing.billing_router',
        'services.backend.api.billing.database',
        'services.backend.api.support.support_router',
        'services.backend.api.store.store_router',
        'services.backend.api.service.service_router',
        'services.backend.api.notification.notification_router',
        'services.backend.api.email.email_service',
        'services.backend.api.control.router',
        'services.backend.api.control.service',
        'services.backend.api.ai.ai_router',
        'services.backend.api.ai.ollama_service',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'notebook',
        'test',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='EnergyLinkSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
