(function(){
  if (window.__extendInformation) return; window.__extendInformation=true;
  function infoApi(path){ const base=(window.__CONFIG&&window.__CONFIG.apiBase)?String(window.__CONFIG.apiBase).replace(/\/$/,''):''; return (base?base:'')+path; }
  function injectInfoStyles(){ if(document.getElementById('info-style')) return; const s=document.createElement('style'); s.id='info-style'; s.textContent=`.panel{background:#0d1f2f;border:1px solid #29465c;border-radius:18px;box-shadow:0 20px 40px rgba(0,0,0,.35);padding:18px} .headline{font-size:28px;color:#63d1ff;margin:0 0 8px} .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px} @media(max-width:900px){.grid{grid-template-columns:1fr}} .box{border:1px solid #274b61;border-radius:14px;padding:12px} .tiny{font-size:12px;color:#9bd0e8} .primary-btn{border:1px solid #2c6b8a;background:#113246;color:#cce8ff;border-radius:12px;padding:10px 14px;cursor:pointer}`; document.head.appendChild(s); }
  async function renderInformation(){ const area=document.getElementById('content-area'); injectInfoStyles(); area.innerHTML=`<div class="panel"><div class="headline">Information</div><div class="grid"><div class="box"><h3 style="color:#9bd0e8">Project</h3><div class="tiny" id="inf-project"></div><img id="inf-qr" alt="QR" style="margin-top:8px;max-width:240px;border-radius:12px"></div><div class="box"><h3 style="color:#9bd0e8">Public Ingest</h3><div class="tiny">Token</div><div id="inf-token" style="color:#cce8ff;word-break:break-all;margin-bottom:10px"></div><button class="primary-btn" id="inf-copy">Copy Token</button></div></div><div class="box" style="margin-top:18px"><h3 style="color:#9bd0e8">Devices</h3><div id="inf-devices" class="tiny"></div></div><div class="box" style="margin-top:18px"><h3 style="color:#9bd0e8">User Login</h3><div class="tiny">Project ID</div><div id="inf-pid" class="tiny"></div><div style="display:flex;gap:8px;margin:8px 0"><input id="inf-user" placeholder="Username" style="flex:1;padding:8px;border-radius:8px;border:1px solid #274b61;background:#113246;color:#cce8ff"><input id="inf-pass" placeholder="Password" type="password" style="flex:1;padding:8px;border-radius:8px;border:1px solid #274b61;background:#113246;color:#cce8ff"><button class="primary-btn" id="inf-save">Save/Update</button></div><div class="tiny">Users</div><div id="inf-users" class="tiny"></div><div style="display:flex;gap:8px;margin-top:8px"><button class="primary-btn" id="inf-refresh-users">Refresh</button><button class="primary-btn" id="inf-show-login-qr">Show Login QR</button></div><img id="inf-login-qr" alt="Login QR" style="margin-top:8px;max-width:240px;border-radius:12px;display:none"></div></div>`; document.getElementById('inf-copy').onclick=()=>{ const t=document.getElementById('inf-token').textContent; navigator.clipboard.writeText(t); }; await loadInfo(); if(typeof window.highlightNav==='function') window.highlightNav('information'); }
  let infoPid=null; async function loadInfo(){ try{ const act=await fetch(infoApi('/api/active')); const aj=await act.json(); infoPid=aj.active; if(!infoPid){ document.getElementById('inf-project').textContent='No active project'; return; } const pi=await fetch(infoApi(`/api/projects/${infoPid}/info`)); if(pi.ok){ const pj=await pi.json(); document.getElementById('inf-project').textContent=`${pj.project_name} (${infoPid})`; document.getElementById('inf-qr').src=pj.qr_code||''; } const tokres=await fetch(infoApi(`/api/projects/${infoPid}/ingest_token`)); if(tokres.ok){ const tj=await tokres.json(); document.getElementById('inf-token').textContent=tj.ingest_token||''; } const dres=await fetch(infoApi(`/api/projects/${infoPid}/devices`)); const dj=await dres.json(); const list=dj.devices||[]; const dv=document.getElementById('inf-devices'); dv.innerHTML=list.map(d=>`<div>${d.name||('Device #'+d.id)} — addr ${d.modbus_slave||d.address}</div>`).join(''); document.getElementById('inf-pid').textContent=infoPid; bindLoginControls(); refreshUsers(); }catch(e){ console.error(e); }}
  async function refreshUsers(){ if(!infoPid) return; try{ const r=await fetch(infoApi(`/api/projects/${infoPid}/users`)); const j=await r.json(); const u=j.users||[]; const el=document.getElementById('inf-users'); el.innerHTML=u.length? u.map(x=>`<span style="display:inline-block;margin:4px;padding:6px 10px;border:1px solid #2c6b8a;border-radius:12px;background:#113246;color:#cce8ff">${x}</span>`).join(''):`<span>None</span>`; }catch(e){ }
  }
  function bindLoginControls(){ const sv=document.getElementById('inf-save'); const rf=document.getElementById('inf-refresh-users'); const sh=document.getElementById('inf-show-login-qr'); if(sv){ sv.onclick=async()=>{ const u=document.getElementById('inf-user').value.trim(); const p=document.getElementById('inf-pass').value; if(!u||!p||!infoPid) return; await fetch(infoApi(`/api/projects/${infoPid}/users/upsert`),{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ username:u, password:p, role:'user' }) }); document.getElementById('inf-pass').value=''; refreshUsers(); }; } if(rf){ rf.onclick=refreshUsers; } if(sh){ sh.onclick=async()=>{ if(!infoPid) return; const r=await fetch(infoApi(`/api/projects/${infoPid}/login_qr`)); const j=await r.json(); const img=document.getElementById('inf-login-qr'); img.src=j.qr||''; img.style.display='block'; }; }
  }
  const orig=window.showPage; window.showPage=function(page){ if(page==='information'){ renderInformation(); return; } return orig(page); };
})();
